---
# Vector
- name: Install Vector
  become: true
  block:
  - name: Get RPM packages
    ansible.builtin.get_url:
      url: "https://packages.timber.io/vector/{{ vector_version }}/{{ item }}-{{ vector_version }}-1.x86_64.rpm"
      dest: "./{{ item }}.rpm"
    with_items: "{{ vector_packages }}"
  - name: Install RPM packages
    become: true
    ansible.builtin.yum:
      name: "{{ item }}.rpm"
      disable_gpg_check: true
    with_items: "{{ vector_packages }}"
  - name: Copy server configuration file
    become: true
    ansible.builtin.template:
      src: vector.toml
      dest: "/etc/vector/vector.toml"
      owner: "0"
      group: "0"
      mode: "0664"
    notify: Start vector service
